### ISSUE TITLE
Confusion: schematic and description don't match

### ISSUE THREAD

**Issue by JonnyPhenomenon** [TrojanPinata/DIY-Mic#1]
in your description you said "The two capacitors on the right need to be filpped 180 degrees so the polarities are swapped" - but your schematic shows only one cap at the bottom with negative on the right, and the top three are negative on the left.  

...I see in your picture of the completed board that you have installed the two caps on the right side with negative on the right...

Why did you have to make this change?  and could you update the diagram to reflect the change? 

What does the back of this board look like?

**Comment by TrojanPinata** [comment]
I saw this a couple of weeks ago and flipped the capacitors in the diagram. To clarify, all that means is that you take the two on the far right (one above and below the V+ and GND inputs) and swap which pin goes in which hole. The reason for this is due to polarity of capacitors and having them reversed would mean they never charge (you can read a more detailed explanation someone left on the stripboard image in the gdrive). I didn't really make that obvious in this write up so I apologize, I should have been more clear what I was referencing (and replying in a timely manner lol). As for the back of this board, it looks exactly the same, nothing different from the original. I actually didn't take any pictures of the back when I put it together or I would have posted them here, but it's glued in now and I'm afraid to disassemble it too much. If I do find something I'll update the readme to show a more detailed view from all angles.
