### ISSUE TITLE
Audio grabber and potentiometer connection 

### ISSUE THREAD

**Issue by janse96** [TrojanPinata/DIY-Mic#2]
Hi! I'm happy that I came across your github and that you explained what has to be changed in the schematic, but I couldnt find any info about how to connect the amp to the grabber (the side with the 3 cables). I first used one of the cinch cables but while testing I noticed the only sound i get is when i touch the AUX connector so i changed the connection to that cable. I'm also unsure on how to connect the potentiometer correctly. I just used a 501 potentiometer instead of the rotary switch and I don't know if that's the problem or not, but a variable resistor should do the job just fine.

**Comment by TrojanPinata** [comment]
I did the same thing you did with the potentiometer. I couldn’t find a rotary switch either and I ended up using a 1k potentiometer and it worked fine (granted you are using a THAT 1512 as the TI chips are screwy and have different gain thresholds, which you should then just use a 3k resistor or something). That alone shouldn’t cause a problem. Connecting should be as simple as using a Dupont connector on the potentiometer and a white JST connector for the board. If you’re really unsure you could just solder the positive to the right or left most pin and the other wire to the center pin (on the potentiometer that is).

As for the connections, I also found the JST connectors (the white connectors with the metal insert grabber things) to be kind of a pain. Tbh, I soldered them together by using a few tiny drips of solder on the cables to the metal grabbers and then forcing them in with tweezers. The whole thing is kind of scuffed (similar to splicing the hair thin mic wire with the standard size audio cable). I’m not exactly sure which connection you switched but it should be from the aux input to the mic, which is what it sounds like you did. Really the only thing I can advise is to check your connections and shielding. My shielding on the mic (the wire mesh) is really finicky and if it as so much as shakes it will press up against the transistor and cut audio. Stuff like that doesn’t sound too important but I thought it was being caused by something else for the longest time and resoldered so many connections.

This is kind of a mess and I'm making some assumptions, but I hope that helps!

**Comment by janse96** [comment]
thanks for replying so fast! I already noticed some things that couldnt be right yesterday. For example the voltage was nowhere 15V and it all came back to the fact that i mistakenly soldered the GND connection from board to the free GND pin on the audio grabber PCB. I noticed the voltage there was just 0.3V but after resoldering it directly to the black  cable from the USB cable i got the right voltages and even sound! The only thing still bothering me is that a change from the potentiometer doesnt really affect the volume and the volume stays pretty low and to hear anything i have to raise my PC volume up quite a bit. Any idea of why that is? Also i get alot of noise when the capsule is not grounded to anything. No problem when i touch it or hold it but something isnt right.

**Comment by TrojanPinata** [comment]
From my experience quiet audio is caused by the resistance in the potentiometer being too high for the gain pin on the chip. What the potentiometer controls is gain, and from what I can tell it's pretty sensitive. Make sure your potentiometer is linear (as opposed to logarithmic) and relatively low resistance, say around 1k. If after changing the potentiometer the volume is still really low, swap it for a low resistance resistor (like 100 - 500) and try that. If you're sound improves or is too loud you can tune appropriately from there and then if you determine the potentiometer is the problem, swap it out or insert a resistor at a comfortable volume. I've had cheap potentiometers burn out on me and they either become like shorted wires or broken circuits where no current passes through. If swapping it for lower and lower resistances doesn't change the situation and stright up bridging the connection doesn't improve it and you still have sound but its really quiet, then I think there is some other underlying problem that I'm not sure about. 

Also, assuming you are on Windows, check your sound device settings and make sure volume is around 80/90 or whatever you are comfortable with. For some reason on first plug in mine was really low so double check that if you haven't already. 

As for the capsule, yeah. That's really all. It's super noisy if it’s not perfectly balanced and I don't know a way to fix it. I spent a while trying to make a version two of just the capsule module, but I haven’t figured out a way to make it look good while maintaining the grounding and wire contacts. It's supposed to be connected to the ground wire of the mic but from my experience it almost never connects completely and makes a decent noise dampener. The best I could do was increasing the depth of the mesh to give it a ton of clearance and soldering everything together to make a perfect seal. I found that the THAT chip cleaned up a bit of the noise, but overall, it’s just annoying enough that I either hold the sheathed cable when doing super high quality recording or use a audio editor to clean it up in post (crisper or whatever in discord makes it unnoticeable). Realistically you could probably run another cable (one of the enameled thin ones) on the outside solely for the purpose of grounding (which I might actually do now that I think about it) but realistically there are a few ways to try and fix the noisiness of the capsule. 

Sorry for the novel, hopes this sheads some light on getting those last few things fixed.

**Comment by janse96** [comment]
I appreciate every detail! I will play around with the gain settings and see if anything changes… for the grounding of the capsule however I might just live with it if everything else works out ok. I used all parts exactly like the video proposes just without the swap to usb c, the potentiometer and the overall look/housing. I got some aluminum mesh and will use that for the capsule housing but I haven’t decided yet how the overall look of the mic should be. I’m thinking of buying a boom arm and using your housing for the capsule to insert it in the spider. I might still have some time to come up with something different but I’ll focus on the electronics first. It should work properly before it looks good :) thanks for the help!
